name: Unit test action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Unit test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Cache dependencies
        uses: actions/cache@v2
        id: cache  # name for referring later
        with:
          path: ./.env/  # what we cache: the virtualenv
          # The cache key depends on requirements.txt
          key: ${{ runner.os }}-env-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-env-

      - name: Install dependencies and run pytest
        run: |
          echo "------------- Installing dependencies, running pytest and coverage --------"
          NPM=package.json
          for file in *; do
            if [ -d "$file" ]; then
              if test -f "$file"/"$NPM"; then
                echo "$file"/"$NPM"
                npm run test --prefix "$file"
              fi
            fi
          done